### ISSUE TITLE
Drop-down missing from Cafes

### ISSUE THREAD

**Issue by jrohan1** [dirty-bits/uni-bites#59]
Drop-down menu is no longer visible on Cafe's in Nav-bar
Also blue box border missing from links on hover in nav-bar

**Comment by aflaherty13** [comment]
The issue was that the database was not getting populated correctly after removing the hard-coded values and loading the cafes from the database. The code was attempting to load from the mongodb store but the values were not there, or the mongodb connection string was incorrect. This was compounded by the fact that the populate-db.js function was not always working, this is fixed entirely (so that it is entirely asynchronous) in a seperate branch but the currect develop branch should work if the database is populated with cafes.

I have added tests that check if the dropdown is populated to the the [homepage.spec.js](https://github.com/dirty-bits/uni-bites/blob/develop/specs/ui-tests/homepage.spec.js) in develop. This should verify if everything works when we run the tests.
